site_name: MiCADO
repo_url: https://github.com/micado-scale/ansible-micado
theme:
  name: material
  logo: img/micado-fav.png
  favicon: img/micado-fav.png
  palette:
    primary: deep purple
    accent: yellow
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
nav:
  - MiCADO:
    - index.md
    - Architecture: arch.md
  - Install:
    - install/index.md
    - Requirements: install/requirements.md
    - Quick Start: install/quick-start.md
    - CLI Install: install/cli-install.md
    - Ansible Install: install/ansible-install.md
  - Usage:
    - usage/index.md
    - Dashboard: usage/dashboard.md
    - CLI: usage/cli.md
    - REST API: usage/restapi.md
    - Admin: usage/admin.md
  - Application Description:
    - adt/index.md
    - Containers:
      - adt/containers/index.md
      - Communication: adt/containers/services.md
      - Exposure: adt/containers/expose.md
      - Volumes: adt/containers/volumes.md
      - Sidecars: adt/containers/sidecars.md
      - Advanced: adt/containers/custom.md
      - API Reference: adt/containers/specification.md
    - Virtual Machines:
      - adt/vms/index.md
      - OpenStack: adt/vms/openstack.md
      - EC2: adt/vms/ec2.md
      - CloudBroker: adt/vms/cloudbroker.md
      - CloudSigma: adt/vms/cloudsigma.md
      - Azure: adt/vms/azure.md
      - Google: adt/vms/google.md
      - Oracle: adt/vms/oracle.md
    - Policies:
      - adt/policies/index.md
      - Monitoring: adt/policies/monitoring.md
      - Scaling: adt/policies/scaling.md
      - Networking: adt/policies/networking.md
      - Secrets: adt/policies/secrets.md
  - Demos:
    - demos/index.md
    - stressng: demos/stressng.md
  - Release Notes:
    - What's New: changelog/index.md
    - Changelog: changelog/changelog.md

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - admonition
  - attr_list
  - def_list
  - swaggermarkdown:
      file: tools/swagger.json
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true